main: tk.mctechniclp.devathlon2bukkit.Main
name: DevathlonRound2Bukkit
depend: [PacketListenerApi]
version: 1.0
author: McTechnicLP
description: Bukkit Plugin for the second round of GommeHD.nets Devathlon
